---
name: Daily GraphQL Scrape and Commit
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:  # This allows manual triggering
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run GraphQL query and update data
        run: python fetch_data.py
      - name: Create meta.json file
        run: echo {\"last_updated\":\"$(date --iso-8601=seconds -u)\"} > $GITHUB_WORKSPACE/meta.json
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "TJs-Scraper" && git config user.email "scraper@users.noreply.github.com"
          
          git add .

          git commit -m "Data update $(date -u) [skip ci]"
          git push
